### ISSUE TITLE
how to write the detect notes to midi track ?

### ISSUE THREAD

**Issue by zkbqhuang** [liuanlin-mx/MXTune#14]
how to write the detect notes to midi track in daw?

**Comment by liuanlin-mx** [comment]
![2](https://github.com/liuanlin-mx/MXTune/assets/20225987/8c46a50a-cc64-4edb-9543-f9ed46dbb7ea)

**Comment by zkbqhuang** [comment]
I use ardour on Ubuntu system , I can 't do the step 5 in it .

**Comment by liuanlin-mx** [comment]
![1](https://github.com/liuanlin-mx/MXTune/assets/20225987/01d62e26-7f1a-4b29-b01f-c13993a0dd72)
![2](https://github.com/liuanlin-mx/MXTune/assets/20225987/60bc58dc-8394-488b-8ae3-843194c2c55b)

**Comment by zkbqhuang** [comment]
Thank you for your reply, it has been very helpful to me
