### ISSUE TITLE
save plugin state

### ISSUE THREAD

**Issue by Mrugalla** [liuanlin-mx/MXTune#4]
the plugin does not remember its state, which makes it unusable unfortunately. look into this tutorial to fix it:
https://docs.juce.com/master/tutorial_audio_processor_value_tree_state.html

**Comment by liuanlin-mx** [comment]
I tested it on repaer and ardour and it worked fine

windows? or linux?
Which daw do you use?

**Comment by Mrugalla** [comment]
windows 10. bitwig 4.6

**Comment by slangbein** [comment]
MXTune on Reaper 675 on Linux Mint 21 Cinnamon
everything works as expected; good job. Thank you
plugin state is saved across re-opening of project

**Comment by Mrugalla** [comment]
is this fix in the dll of the release section already? because the issue persists

**Comment by liuanlin-mx** [comment]
No new versions have been released.

This is a temporary version
[aec9cfd1.tar.gz](https://github.com/liuanlin-mx/MXTune/files/10713781/aec9cfd1.tar.gz)

**Comment by Mrugalla** [comment]
oh yes! that version works :) ok let's close this issue then

**Comment by edrickblade** [comment]
hi liuanlin, congratulations for such a great project (MXTune), I want to give you an idea, how if you use paulstretch library instead of autotalent for a better pitch handling and better stretch audio quality?

**Comment by liuanlin-mx** [comment]
> hi liuanlin, congratulations for such a great project (MXTune), I want to give you an idea, how if you use paulstretch library instead of autotalent for a better pitch handling and better stretch audio quality?

I tried the paulxstretch plugin.
It has very noticeable distortion

**Comment by edrickblade** [comment]
> > hi liuanlin, congratulations for such a great project (MXTune), I want to give you an idea, how if you use paulstretch library instead of autotalent for a better pitch handling and better stretch audio quality?
> 
> I tried the paulxstretch plugin. It has very noticeable distortion

Great to know that! however, MXTune is a great pitch plugin, and I know you going to continue developing for good! Thanks for that jewel.
