### ISSUE TITLE
Errors in Lunux

### ISSUE THREAD

**Issue by glitterball** [liuanlin-mx/MXTune#8]
Hi,
I cannot get this to work in Linux.
Ardour returns a 'Invalid Module Path' error.
I have tried guessing the .vst3 folder structure to place .so file, but no joy.

Where should the .so file be placed?

**Comment by liuanlin-mx** [comment]
$HOME/.vst or /usr/lib/vst

Only 64-bit systems are supported

I've only tested it on ubuntu (20.04/18.04)

**Comment by glitterball** [comment]
Thanks - it's working now. I had stupidly presumed it was a vst3 and not vst.
Thanks for the plugin - very handy to have in Linux (Kubuntu 22.04) .
